SELECT * FROM TAB;
--SELECT * FROM STUDENT s ;
--SELECT  * FROM PROFESSOR p ;

SELECT * FROM DEPARTMENT d  ;

-- 부서 테이블의 모든 정보를 조회
SELECT  DEPTNO, DEPTNO, DEPTNO 
FROM DEPARTMENT d ;

--부서 테이블의 부서 이름, 부서 번호 출력
SELECT DNAME , DEPTNO 
FROM DEPARTMENT d;

SELECT  * 
FROM  STUDENT s ;

SELECT
	DEPTNO,
	COUNT(*) CNT,
	AVG(HEIGHT) AVG
FROM
	STUDENT 
WHERE
	DEPTNO < 201
GROUP BY
	DEPTNO
HAVING
	COUNT(*) >= 5;

SELECT  * 
FROM STUDENT
ORDER BY GRADE DESC, STUDNO;

--RESULT SET 행 TUPLE//행집합 중복제거:DISTINCT/
--학생 테이블의 학과 번호 출력,중복 제거
SELECT DISTINCT DEPTNO
FROM  STUDENT;

SELECT * 
FROM STUDENT;
ORDER BY GRADE DESC, STUDNO;

--학생 테이블의 학과번호, 학년에 대한 출력 ,중복 제거
SELECT DISTINCT GRADE ,DEPTNO 
FROM STUDENT;

-- 부서테이블에서 부서 이름은 "부서이름" 부서번호는 "부서 번호"라는 별명을 붙여서 조회
SELECT  DNAME 부서이름,DEPTNO AS "부서 번호"
FROM  DEPARTMENT d ;

SELECT * 
FROM STUDENT
WHERE HEIGHT >= 170 OR WEIGHT >=70;

--학생 테이블에서 학번과 이름을 연결하여 STUDENT라는 별칭을 붙인 결과 조회
SELECT STUDNO || ' ' || NAME STUDENT, CONCAT(CONCAT(STUDNO,' '), NAME) 
FROM STUDENT;0